# Generated by Django 4.2.17 on 2025-02-16 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0002_class_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__role': 'student'}, related_name='class_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
