# Generated by Django 4.2.17 on 2025-02-07 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_comment_created_at_alter_taskanswer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 16, 10, 57, 375965, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 16, 10, 57, 374962, tzinfo=datetime.timezone.utc)),
        ),
    ]
