# Generated by Django 4.2.17 on 2025-02-08 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_alter_comment_created_at_alter_taskanswer_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Message',
        ),
    ]
