# Generated by Django 4.2.17 on 2025-02-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_message_chat_delete_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
