# Generated by Django 4.2.17 on 2025-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, default='static/profile/default-pfp.jpg', null=True, upload_to='profile/pfp/'),
        ),
    ]
