# Generated by Django 4.2.17 on 2025-01-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cash',
            field=models.FloatField(default=0),
        ),
    ]
