# Generated by Django 4.2.17 on 2025-01-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_profile_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
